// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2025 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2021.3.57f2";
    extern const char* const UnityVersionDigits = "2021.3.57";
    extern const char* const UnityVersionSuffix = "f2";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 57;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.3.57f2_45bc4c630002";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.57f2_45bc4c630002";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.57f2 (45bc4c630002)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 4570188;

    extern const UInt64 UnityVersionDate = 1759317384;
    extern const char* const UnityVersionBranch = "2021.3/respin/2021.3.57f1-0329e0aded79";
    extern const char* const UnityVersionDisplay = "2021.3.57f2";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.57f2.git.4570188";
    extern const char* const UnityVersionRevision = "45bc4c630002";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.57f2 (45bc4c630002)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.57f2";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2025 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 57
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.3.57f2_45bc4c630002"
    #define UNITY_VERSION_PARENS_HASH "2021.3.57f2 (45bc4c630002)"
    #define UNITY_VERSION_BLD 4570188
    #define UNITY_VERSION_WIN "2021.3.57.4570188"

#endif // !RC_INVOKED
